"""empty message

Revision ID: 025cba6fc764
Revises: 8f5215f0fc7b
Create Date: 2021-10-02 00:41:49.686592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '025cba6fc764'
down_revision = '8f5215f0fc7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'eisenhower_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('tasks_categories', sa.Column('task_id', sa.Integer(), nullable=False))
    op.alter_column('tasks_categories', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('tasks', 'tasks_categories', type_='foreignkey')
    op.create_foreign_key(None, 'tasks_categories', 'tasks', ['task_id'], ['id'])
    op.drop_column('tasks_categories', 'tasks_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks_categories', sa.Column('tasks_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tasks_categories', type_='foreignkey')
    op.create_foreign_key('tasks', 'tasks_categories', 'tasks', ['tasks_id'], ['id'])
    op.alter_column('tasks_categories', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('tasks_categories', 'task_id')
    op.alter_column('tasks', 'eisenhower_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
