"""empty message

Revision ID: 697d28f0aac4
Revises: 025cba6fc764
Create Date: 2021-10-02 10:30:56.713209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '697d28f0aac4'
down_revision = '025cba6fc764'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks_categories', sa.Column('task_id', sa.Integer(), nullable=False))
    op.alter_column('tasks_categories', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('tasks_categories_category_id_fkey', 'tasks_categories', type_='foreignkey')
    op.drop_constraint('tasks_categories_tasks_id_fkey', 'tasks_categories', type_='foreignkey')
    op.create_foreign_key(None, 'tasks_categories', 'categories', ['category_id'], ['id'])
    op.create_foreign_key(None, 'tasks_categories', 'tasks', ['task_id'], ['id'])
    op.drop_column('tasks_categories', 'tasks_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks_categories', sa.Column('tasks_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tasks_categories', type_='foreignkey')
    op.drop_constraint(None, 'tasks_categories', type_='foreignkey')
    op.create_foreign_key('tasks_categories_tasks_id_fkey', 'tasks_categories', 'tasks', ['tasks_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('tasks_categories_category_id_fkey', 'tasks_categories', 'categories', ['category_id'], ['id'], ondelete='CASCADE')
    op.alter_column('tasks_categories', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('tasks_categories', 'task_id')
    # ### end Alembic commands ###
