"""empty message

Revision ID: 8f5215f0fc7b
Revises: 2f404620ec44
Create Date: 2021-10-01 15:45:14.643427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f5215f0fc7b'
down_revision = '2f404620ec44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('eisenhower_id', sa.Integer(), nullable=False))
    op.drop_constraint('tasks_eisenhowers_id_fkey', 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'eisenhowers', ['eisenhower_id'], ['id'])
    op.drop_column('tasks', 'eisenhowers_id')
    op.add_column('tasks_categories', sa.Column('task_id', sa.Integer(), nullable=False))
    op.alter_column('tasks_categories', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('tasks_categories_category_id_fkey', 'tasks_categories', type_='foreignkey')
    op.drop_constraint('tasks_categories_tasks_id_fkey', 'tasks_categories', type_='foreignkey')
    op.create_foreign_key(None, 'tasks_categories', 'tasks', ['task_id'], ['id'])
    op.create_foreign_key(None, 'tasks_categories', 'categories', ['category_id'], ['id'])
    op.drop_column('tasks_categories', 'tasks_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks_categories', sa.Column('tasks_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tasks_categories', type_='foreignkey')
    op.drop_constraint(None, 'tasks_categories', type_='foreignkey')
    op.create_foreign_key('tasks_categories_tasks_id_fkey', 'tasks_categories', 'tasks', ['tasks_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('tasks_categories_category_id_fkey', 'tasks_categories', 'categories', ['category_id'], ['id'], ondelete='CASCADE')
    op.alter_column('tasks_categories', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('tasks_categories', 'task_id')
    op.add_column('tasks', sa.Column('eisenhowers_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key('tasks_eisenhowers_id_fkey', 'tasks', 'eisenhowers', ['eisenhowers_id'], ['id'], ondelete='CASCADE')
    op.drop_column('tasks', 'eisenhower_id')
    # ### end Alembic commands ###
